#!/bin/bash

# add -n for dry run 
# add --delete to sync full and remove old files  

rsync -av -m --include='*/' \
	--include='*.c' --include='*.h' --include='makefile' --include='pub*.txt' \
	--exclude='*' \
    gex fs gtree \
    "/Users/matt/My Drive/ProjectBak/"
    
